version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i # install npm packages
      - save_cache: # save packages in cache so further jobs dont need to reinstall them
          key: "npm-packages"
          paths:
            - "/src/node_modules"
      - run:
          name: "build comman defined in package.json"
          command: "npm run lint"
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i # install npm packages, but as it is using restored, it won't need to download them. It will use the local files to install, making instalation process faster.
      - run:
          name: "testing command defined in package.json"
          command: "npm run test"
  analyse:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run:
          name: "audit command defined in package.json"
          command: "npm audit"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test
